<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInite0df3bf5deb41a2662e6308b75a472e2
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('StripeWPFS\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \StripeWPFS\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInite0df3bf5deb41a2662e6308b75a472e2', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \StripeWPFS\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInite0df3bf5deb41a2662e6308b75a472e2', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\StripeWPFS\Composer\Autoload\ComposerStaticInite0df3bf5deb41a2662e6308b75a472e2::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
